[package]
name = "double_tournament"
version = "0.1.0"
edition = "2018"
authors = ["Marcel Kaufmann <flocksserver@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
round_robin_tournament = "0.1.0"